<?php

use Illuminate\Database\Seeder;
use App\Models\Asignatura;

class AsignaturasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        
        $this->crearAsig(1, "ANALISIS NUMERICO");
        $this->crearAsig(1, "CINEMATICA Y DINAMICA");
        $this->crearAsig(1, "CINEMATICA Y DINAMICA (2016)");
        $this->crearAsig(1, "DIBUJO");
        $this->crearAsig(1, "DIBUJO  (2016)");
        $this->crearAsig(1, "ECUACIONES DIFERENCIALES (2016)");
        $this->crearAsig(1, "ESTADISTICA");
        $this->crearAsig(1, "ESTADISTICA PARA ING. ELEC. ELECTRONICA");
        $this->crearAsig(1, "ESTATICA");
        $this->crearAsig(1, "ESTATICA (2016)");
        $this->crearAsig(1, "FUNDAMENTOS DE ESTADISTICA");
        $this->crearAsig(1, "MATEMATICAS AVANZADAS");
        $this->crearAsig(1, "MECANICA  (2016)");
        $this->crearAsig(1, "PROBABILIDAD");
        $this->crearAsig(1, "PROBABILIDAD Y ESTADISTICA");
        $this->crearAsig(1, "REPRESENTACIONES GRAFICAS");
        $this->crearAsig(1, "DIBUJO INDUSTRIAL");
        $this->crearAsig(1, "FUNDAMENTOS DE PROBABILIDAD Y ESTADISTICA");
        $this->crearAsig(1, "LABORATORIO MECANICA (2016)");
        $this->crearAsig(2, "ACUSTICA Y OPTICA");
        $this->crearAsig(2, "ELECTRICIDAD Y MAGNETISMO");
        $this->crearAsig(2, "ELECTROMAGNETISMO Y OPTICA");
        $this->crearAsig(2, "FISICA  (2016)");
        $this->crearAsig(2, "FISICA EXPERIMENTAL (2016)");
        $this->crearAsig(2, "FISICOQUIMICA PARA ING. AMBIENTAL");
        $this->crearAsig(2, "FUNDAMENTOS DE FISICA");
        $this->crearAsig(2, "FUNDAMENTOS DE OPTICA");
        $this->crearAsig(2, "FUNDAMENTOS DE TERMODINAMICA Y ELECTROMAGNETISMO");
        $this->crearAsig(2, "INTRODUCCION A  LA FISICA DEL ESTADO SOLIDO");
        $this->crearAsig(2, "LAB FUNDAM TERMODI ELECTROM");
        $this->crearAsig(2, "LAB SISTEMAS QUIMICOS EN ING");
        $this->crearAsig(2, "LAB TERMODINAMICA");
        $this->crearAsig(2, "Lab. abierto de cinematica y dinamica");
        $this->crearAsig(2, "Lab. abierto de estatica");
        $this->crearAsig(2, "LAB. DE QUIMICA (2016)");
        $this->crearAsig(2, "LAB. DE QUIMICA DE C. DE LA TIERRA (2016)");
        $this->crearAsig(2, "LAB. QUIMICA INORGANICA");
        $this->crearAsig(2, "LABORATORIO DE ELECTRICIDAD Y MAGNETISMO");
        $this->crearAsig(2, "QUIMICA (2016)");
        $this->crearAsig(2, "QUIMICA DE CIENCIAS DE LA TIERRA (2016)");
        $this->crearAsig(2, "QUIMICA INORGANICA");
        $this->crearAsig(2, "SISTEMAS QUIMICOS EN INGENIERIA");
        $this->crearAsig(2, "TERMODINAMICA");
        $this->crearAsig(2, "SISTEMAS TERMODINAMICOS - ELECTROMAGNETISMO");
        $this->crearAsig(2, "BIOLOGIA");
        $this->crearAsig(2, "FISICA CUANTICA");
        $this->crearAsig(2, "LABORATORIO DE QUIMICA ORGANICA");
        $this->crearAsig(3, "ALGEBRA (2016)");
        $this->crearAsig(3, "ALGEBRA LINEAL");
        $this->crearAsig(3, "ALGEBRA LINEAL (2016)");
        $this->crearAsig(3, "CALCULO INTEGRAL");
        $this->crearAsig(3, "CALCULO INTEGRAL (2016)");
        $this->crearAsig(3, "CALCULO VECTORIAL");
        $this->crearAsig(3, "CALCULO VECTORIAL (2016)");
        $this->crearAsig(3, "CALCULO Y GEOMETRIA ANALITICA (2016)");
        $this->crearAsig(4, "ADMINISTRACION EN INGENIERIA");
        $this->crearAsig(4, "EDIFICACION");
        $this->crearAsig(4, "MOVIMIENTO DE TIERRAS");
        $this->crearAsig(4, "PREPARACION DE CONCURSO DE OBRA PUBLICA");
        $this->crearAsig(4, "PROCEDIMIENTOS CONTRUCTIVOS DE ELEMENTOS ESTRUCT");
        $this->crearAsig(4, "RECURSOS DE LA CONSTRUCCION");
        $this->crearAsig(4, "PROGRAMACION Y PRESUPUESTACIÓN");
        $this->crearAsig(4, "LAB. MOVIMIENTO DE TIERRAS");
        $this->crearAsig(5, "ANALISIS ESTRUCTURAL");
        $this->crearAsig(5, "DIMENSIONAMIENTO DE  ELEMENTOS  ESTRUCTURALES");
        $this->crearAsig(5, "DISEÑO ESTRUCTURAL");
        $this->crearAsig(5, "ESTRUCTURAS ISOSTATICAS");
        $this->crearAsig(5, "MECANICA DE MATERIALES I");
        $this->crearAsig(5, "MECANICA DE MATERIALES II");
        $this->crearAsig(5, "ESTRUCTURAS DE CONCRETO");
        $this->crearAsig(5, "ESTRUCTURAS DE MAMPOSTERIA");
        $this->crearAsig(5, "LAB. MECANICA DE MATERIALES I");
        $this->crearAsig(5, "LAB. MECANICA DE MATERIALES II");
        $this->crearAsig(6, "FOTOGRAMETRIA");
        $this->crearAsig(6, "GESTION AMBIENTAL");
        $this->crearAsig(6, "INTRODUCCION A  BASES DE DATOS ESPACIALES");
        $this->crearAsig(6, "PERCEPCION REMOTA II");
        $this->crearAsig(6, "PROYECTO GEOMATICO");
        $this->crearAsig(6, "SISTEMAS DE INFORMACION GEOGRAFICA I");
        $this->crearAsig(6, "SISTEMAS DE INFORMACION GEOGRAFICA II");
        $this->crearAsig(6, "PERCEPCION REMOTA I");
        $this->crearAsig(7, "CALCULO DE AJUSTES");
        $this->crearAsig(7, "GEODESIA");
        $this->crearAsig(7, "GEODESIA I");
        $this->crearAsig(7, "GEODESIA II");
        $this->crearAsig(7, "GEODESIA III");
        $this->crearAsig(7, "HIDRAULICA E HIDROLOGIA");
        $this->crearAsig(7, "HIDROLOGIA APLICADA A LA GEOMATICA");
        $this->crearAsig(7, "MODELACION MATEMATICA");
        $this->crearAsig(7, "SISTEMA POSICIONAMIENTO GLOBAL (GPS)");
        $this->crearAsig(7, "SISTEMAS DE POSICION GLOBAL");
        $this->crearAsig(7, "TEORIA DE LOS ERRORES");
        $this->crearAsig(7, "TEORIA DE LOS ERRORES I");
        $this->crearAsig(7, "TEORIA DE LOS ERRORES II");
        $this->crearAsig(7, "PROGRAMACION APLICADA A LA GEOMATICA");
        $this->crearAsig(8, "CIMENTACIONES");
        $this->crearAsig(8, "COMPORTAMIENTO DE SUELOS");
        $this->crearAsig(8, "ESTRUCTURA DE PAVIMENTOS");
        $this->crearAsig(8, "FUND. DE MECANICA DEL MEDIO CONTINUO");
        $this->crearAsig(8, "GEOLOGIA");
        $this->crearAsig(8, "MECANICA DE SUELOS");
        $this->crearAsig(8, "DINAMICA DE SUELOS");
        $this->crearAsig(8, "FUNDAMENTOS DE MECANICA DE ROCAS");
        $this->crearAsig(8, "MECANICA DE SUELOS APLICADA");
        $this->crearAsig(8, "LAB. FUNDAMENTOS DE MECANICA DEL MEDIO CONTINUO");
        $this->crearAsig(8, "LAB. COMPORTAMIENTO DE SUELOS");
        $this->crearAsig(8, "LAB. MECANICA DE SUELOS");
        $this->crearAsig(9, "ANALISIS DE CIRCUITOS ELECTRICOS");
        $this->crearAsig(9, "ANALISIS DE SISTEMAS Y SEÑALES");
        $this->crearAsig(9, "CIRCUITOS ELECTRICOS");
        $this->crearAsig(9, "DINAMICA DE SISTEMAS FISICOS");
        $this->crearAsig(9, "FUNDAMENTOS DE CONTROL");
        $this->crearAsig(9, "FUNDAMENTOS DE INSTRUMENTACION BIOMEDICA");
        $this->crearAsig(9, "LAB. ANALISIS DE  SISTEMAS Y SEÑALES");
        $this->crearAsig(9, "LAB. ANALISIS DE CIRCUITOS ELECTRICOS");
        $this->crearAsig(9, "LAB. CIRCUITOS ELECTRICOS");
        $this->crearAsig(9, "LAB. CONTROL AVANZADO");
        $this->crearAsig(9, "LAB. FUNDAMENTOS DE CONTROL");
        $this->crearAsig(9, "LAB. MEDICION E INSTRUMENTACION");
        $this->crearAsig(9, "LAB. ROBOTICA INDUSTRIAL");
        $this->crearAsig(9, "LAB. SEÑALES Y SISTEMAS");
        $this->crearAsig(9, "LAB. SISTEMAS DE CONTROL");
        $this->crearAsig(9, "MEDICION E INSTRUMENTACION");
        $this->crearAsig(9, "SEÑALES Y SISTEMAS");
        $this->crearAsig(9, "TEMAS SELECTOS DE ING. BIOMEDICA");
        $this->crearAsig(9, "SISTEMAS Y EQUIPOS BIOMEDICOS ELECTRONICOS");
        $this->crearAsig(9, "CONTROL DE SISTEMAS NO LINEALES");
        $this->crearAsig(9, "SISTEMAS EMBEBIDOS EN INSTRUMENTACION Y CONTROL");
        $this->crearAsig(9, "FISIOLOGIA DEL SISTEMA ENDOCRINO Y NERVIOSO");
        $this->crearAsig(9, "INGENIERIA CLINICA");
        $this->crearAsig(9, "TEMAS SELECTOS DE INGENIERIA BIOMEDICA");
        $this->crearAsig(9, "LAB. CONTROL DE SISTEMAS NO LINEALES");
        $this->crearAsig(9, "LAB. SISTEMAS EMBEBIDOS EN INSTRUMENTACION Y CONTROL");
        $this->crearAsig(9, "LABORATORIO FISIOLOGIA DEL SISTEMA ENDOCRINO Y NERVIOSO");
        $this->crearAsig(10, "DETERIORO DE MATERIALES");
        $this->crearAsig(10, "DIBUJO MECANICO E INDUSTRIAL");
        $this->crearAsig(10, "DINAMICA DE MAQUINARIA");
        $this->crearAsig(10, "DISEÑO DE ELEMENTOS DE MAQUINAS");
        $this->crearAsig(10, "DISEÑO DEL PRODUCTO");
        $this->crearAsig(10, "DISEÑO Y MANUFACTURA ASISTIDA POR COMPUTADORA");
        $this->crearAsig(10, "INGENIERIA  AUTOMOTRIZ I");
        $this->crearAsig(10, "INGENIERIA DE DISEÑO");
        $this->crearAsig(10, "INGENIERIA DE MANUFACTURA");
        $this->crearAsig(10, "INGENIERIA DE MATERIALES");
        $this->crearAsig(10, "INGENIERIA DE SUPERFICIES");
        $this->crearAsig(10, "INTRODUCCION A LA INGENIERIA MECANICA");
        $this->crearAsig(10, "LAB INGENIERIA DE MATERIALES");
        $this->crearAsig(10, "LAB MATERIALES II");
        $this->crearAsig(10, "LAB. DE MANUFACTURA  I (2016)");
        $this->crearAsig(10, "LAB. MANUFACTURA III");
        $this->crearAsig(10, "LAB. MATERIALES NO METALICOS");
        $this->crearAsig(10, "LAB. METALURGIA FISICA");
        $this->crearAsig(10, "LAB. MODELADO DE PROCESOS DE MANUFACTURA");
        $this->crearAsig(10, "LAB. PROCESOS DE MANUFACTURA I");
        $this->crearAsig(10, "LABORATORIO DE INGENIERIA DE MANUFACTURA");
        $this->crearAsig(10, "LABORATORIO DE MANUFACTURA II");
        $this->crearAsig(10, "LABORATORIO DE TECNOLOGIA DE MATERIALES");
        $this->crearAsig(10, "MANUFACTURA  II");
        $this->crearAsig(10, "MANUFACTURA I (2016)");
        $this->crearAsig(10, "MANUFACTURA III");
        $this->crearAsig(10, "MATERIALES I");
        $this->crearAsig(10, "MATERIALES II");
        $this->crearAsig(10, "MECANICA DE SOLIDOS");
        $this->crearAsig(10, "METALURGIA FISICA");
        $this->crearAsig(10, "PROCESOS DE MANUFACTURA I");
        $this->crearAsig(10, "PROCESOS DE MANUFACTURA II");
        $this->crearAsig(10, "PROYECTO DE INGENIERIA");
        $this->crearAsig(10, "SEMINARIO DE INGENIERIA");
        $this->crearAsig(10, "SISTEMAS DE MANUFACTURA FLEXIBLE");
        $this->crearAsig(10, "TEMAS SELECTOS DE DISEÑO I");
        $this->crearAsig(10, "TEMAS SELECTOS DE DISEÑO II");
        $this->crearAsig(10, "TEMAS SELECTOS DE INGENIERIA DE DISEÑO I");
        $this->crearAsig(10, "TEMAS SELECTOS DE INGENIERIA DE DISEÑO II");
        $this->crearAsig(10, "TEMAS SELECTOS DE INGENIERIA MATERIALES Y MANUFACTURA I");
        $this->crearAsig(10, "TEMAS SELECTOS DE INGENIERIA MATERIALES Y MANUFACTURA II");
        $this->crearAsig(10, "TEMAS SELECTOS DE MANUFACTURA");
        $this->crearAsig(10, "TEMAS SELECTOS DE MATERIALES");
        $this->crearAsig(10, "TECNOLOGIA DE MATERIALES");
        $this->crearAsig(10, "INGENIERIA AUTOMOTRIZ");
        $this->crearAsig(10, "LAB. INGENIERIA DE DISEÑO");
        $this->crearAsig(10, "LAB. MATERIALES III");
        $this->crearAsig(11, "ADMINISTRACION APLICADA A LA MINERIA");
        $this->crearAsig(11, "ANALISIS QUIMICO");
        $this->crearAsig(11, "CONCENTRACION DE MINERALES");
        $this->crearAsig(11, "DEPOSITOS DE RESIDUOS MINEROS");
        $this->crearAsig(11, "DISEÑO DE OPERACIONES MINERAS");
        $this->crearAsig(11, "EXPLOTACION DE MINAS SUBTERRANEAS");
        $this->crearAsig(11, "FISICOQUIMICA");
        $this->crearAsig(11, "FUNDAMENTOS PARA LA EXPLOTACION DE MINAS");
        $this->crearAsig(11, "GESTION AMBIENTAL EN MINERIA");
        $this->crearAsig(11, "INSTALACIONES MINERO METALURGICAS");
        $this->crearAsig(11, "INTRODUCCION A LA INGENIERIA DE MINAS Y METALURGIA");
        $this->crearAsig(11, "LEGISLACION MINERA");
        $this->crearAsig(11, "MATERIALES Y PROCEDIMIENTOS DE CONSTRUCCION");
        $this->crearAsig(11, "MECANICA APLICADA Y PROCEDIMIENTOS DE CONSTRUCCION");
        $this->crearAsig(11, "PREPARACION Y CONCENTRACION  DE MINERALES");
        $this->crearAsig(11, "VENTILACION");
        $this->crearAsig(11, "VOLADURA DE ROCAS");
        $this->crearAsig(11, "PROYECTOS MINERO METALURGICOS");
        $this->crearAsig(11, "TEMAS SELECTOS");
        $this->crearAsig(11, "FUNDAMENTOS DE METALURGIA EXTRACTIVA");
        $this->crearAsig(11, "HIDRO-ELECTROMETALURGIA");
        $this->crearAsig(11, "MOLlENDA FINA Y ULTRAFINA");
        $this->crearAsig(11, "TEMAS SELECTOS DE MINERIA");
        $this->crearAsig(11, "HIDRO Y PIROMETALURGIA");
        $this->crearAsig(11, "MOLIENDA FINA Y ULTRAFINA");
        $this->crearAsig(12, "AMPLIFICADORES ELECTRONICOS");
        $this->crearAsig(12, "CIRCUITOS INTEGRADOS ANALOGICOS");
        $this->crearAsig(12, "CIRCUITOS PARA COMUNICACIONES");
        $this->crearAsig(12, "DISEÑO DIGITAL");
        $this->crearAsig(12, "DISPOSITIVOS ELECTRONICOS");
        $this->crearAsig(12, "DISPOSITIVOS ELECTRONICOS PROGRAMABLES");
        $this->crearAsig(12, "DISPOSITIVOS Y CIRCUITOS ELECTRONICOS");
        $this->crearAsig(12, "ELECTRONICA DE POTENCIA");
        $this->crearAsig(12, "ELECTRONICA DIGITAL");
        $this->crearAsig(12, "ELECTRONICA PARA TELECOMUNICACIONES");
        $this->crearAsig(12, "FISICA DE SEMICONDUCTORES");
        $this->crearAsig(12, "LAB.  AMPLIFICADORES ELECTRONICOS");
        $this->crearAsig(12, "LAB. AMPLIFICADORES ELECTRONICOS");
        $this->crearAsig(12, "LAB. CIRCUITOS INTEGRADOS ANALOGICOS");
        $this->crearAsig(12, "LAB. CIRCUITOS PARA COMUNICACIONES");
        $this->crearAsig(12, "LAB. DISEÑO DIGITAL");
        $this->crearAsig(12, "LAB. DISPOSITIVOS ELECTRONICOS");
        $this->crearAsig(12, "LAB. DISPOSITIVOS Y CIRCUITOS ELECTRONICOS");
        $this->crearAsig(12, "LAB. ELECTRONICA PARA TELECOMUNICACIONES");
        $this->crearAsig(12, "LAB. MICROPROCESADORES Y MICROCONTROLADORES");
        $this->crearAsig(12, "MEMS PARA RADIOFRECUENCIA");
        $this->crearAsig(12, "MICROPROCESADORES Y MICROCONTROLADORES");
        $this->crearAsig(12, "PROYECTO DE INVESTIGACION DE INGENIERIA ELECTRICA ELECTRONICA");
        $this->crearAsig(12, "SISTEMAS DIGITALES");
        $this->crearAsig(12, "SISTEMAS EMBEBIDOS");
        $this->crearAsig(12, "SISTEMAS OPERATIVOS EN TIEMPO REAL");
        $this->crearAsig(12, "TEMAS SELECTOS DE ELECTRONICA");
        $this->crearAsig(12, "AMPLIFICADORES PARA MICROONDAS");
        $this->crearAsig(12, "SISTEMAS ELECTRONICOS ANALOGICOS");
        $this->crearAsig(12, "SISTEMAS ELECTRONICOS");
        $this->crearAsig(12, "LAB. SISTEMAS ELECTRONICOS ANALOGICOS");
        $this->crearAsig(12, "LAB. SISTEMAS ELECTRONICOS");
        $this->crearAsig(13, "ADMINISTRACION DE PROYECTOS DE SOFTWARE");
        $this->crearAsig(13, "ADMINISTRACION DE REDES");
        $this->crearAsig(13, "ARQUITECTURA DE COMPUTADORAS");
        $this->crearAsig(13, "BASES DE DATOS");
        $this->crearAsig(13, "BASES DE DATOS AVANZADAS");
        $this->crearAsig(13, "BASES DE DATOS DISTRIBUIDAS");
        $this->crearAsig(13, "BASES DE DATOS ESPACIALES");
        $this->crearAsig(13, "COMPILADORES");
        $this->crearAsig(13, "COMPUTACION GRAFICA");
        $this->crearAsig(13, "COMPUTACION GRAFICA E INTERACCION HUMANO-COMPUTADORA");
        $this->crearAsig(13, "COMPUTO MOVIL");
        $this->crearAsig(13, "CRIPTOGRAFIA");
        $this->crearAsig(13, "DEPOSITOS DE DATOS");
        $this->crearAsig(13, "DISEÑO DE INTERFACES, MULTIMEDIA Y REALlDAD VIRTUAL");
        $this->crearAsig(13, "DISEÑO DE SISTEMAS DIGITALES");
        $this->crearAsig(13, "DISEÑO DIGITAL MODERNO");
        $this->crearAsig(13, "DISEÑO DIGITAL VLSI");
        $this->crearAsig(13, "ESTRUCTURA DE DATOS Y ALGORITMOS I");
        $this->crearAsig(13, "ESTRUCTURA Y PROGRAMACION  DE COMPUTADORAS");
        $this->crearAsig(13, "ESTRUCTURAS DISCRETAS");
        $this->crearAsig(13, "FINANZAS EN LA INGENIERIA EN COMPUTACION");
        $this->crearAsig(13, "FUNDAMENTOS DE PROGRAMACION (2016)");
        $this->crearAsig(13, "FUNDAMENTOS DE SISTEMAS EMBEBIDOS");
        $this->crearAsig(13, "INGENIERIA DE SOFTWARE");
        $this->crearAsig(13, "INTELIGENCIA ARTIFICIAL");
        $this->crearAsig(13, "LAB. ADMINISTRACION DE REDES");
        $this->crearAsig(13, "LAB. BASES DE DATOS");
        $this->crearAsig(13, "LAB. COMPUTACION GRAFICA");
        $this->crearAsig(13, "LAB. COMPUTACION GRAFICA E INTERACCION HUMANO-COMPUTADORA");
        $this->crearAsig(13, "LAB. DISEÑO DIGITAL MODERNO");
        $this->crearAsig(13, "LAB. DISPOSITIVOS DE ALMACENAMIENTO E/S");
        $this->crearAsig(13, "LAB. MICROCOMPUTADORAS");
        $this->crearAsig(13, "LAB. ORGANIZACION Y ARQUITECTURA DE COMPUTADORAS");
        $this->crearAsig(13, "LAB. REDES DE DATOS");
        $this->crearAsig(13, "LAB. REDES DE DATOS SEGURAS");
        $this->crearAsig(13, "LENGUAJES DE PROGRAMACION");
        $this->crearAsig(13, "LENGUAJES FORMALES Y AUTOMATAS");
        $this->crearAsig(13, "MICROCOMPUTADORAS");
        $this->crearAsig(13, "MINERIA DE DATOS");
        $this->crearAsig(13, "MODELOS DE PROGRAMACION ORIENTADA A OBJETOS");
        $this->crearAsig(13, "ORGANIZACION Y ARQUITECTURA DE COMPUTADORAS");
        $this->crearAsig(13, "PROGRAMACION BASICA");
        $this->crearAsig(13, "PROGRAMACION ORIENTADA A OBJETOS");
        $this->crearAsig(13, "PROYECTO DE INVESTIGACION");
        $this->crearAsig(13, "REDES DE DATOS SEGURAS");
        $this->crearAsig(13, "SEGURIDAD INFORMATICA AVANZADA");
        $this->crearAsig(13, "SEGURIDAD INFORMATICA BASICA");
        $this->crearAsig(13, "SEGURIDAD INFORMATICA I");
        $this->crearAsig(13, "SEGURIDAD INFORMATICA II");
        $this->crearAsig(13, "SEMINARIO DE TITULACION");
        $this->crearAsig(13, "SEMINARIO DE TITULACION PARA INGENIEROS EN COMPUTACION");
        $this->crearAsig(13, "SISTEMAS DISTRIBUIDOS");
        $this->crearAsig(13, "SISTEMAS EMBEBIDOS AVANZADOS");
        $this->crearAsig(13, "SISTEMAS OPERATIVOS");
        $this->crearAsig(13, "TEMAS SELECTOS DE GRAFICACION");
        $this->crearAsig(13, "TEMAS SELECTOS DE INGENIERIA EN COMPUTACION I");
        $this->crearAsig(13, "TEMAS SELECTOS DE INGENIERIA EN COMPUTACION II");
        $this->crearAsig(13, "TEMAS SELECTOS DE INGENIERIA EN COMPUTACION III");
        $this->crearAsig(13, "TEMAS SELECTOS DE REDES Y SEGURIDAD");
        $this->crearAsig(13, "VERIFICACION Y VALlDACION DE SOFTWARE");
        $this->crearAsig(13, "ARQUITECTURAS CLlENTE/SERVIDOR");
        $this->crearAsig(13, "COMPUTO DE ALTO DESEMPEÑO");
        $this->crearAsig(13, "COMPUTACION GRAFICA AVANZADA");
        $this->crearAsig(13, "DISEÑO ASISTIDO POR COMPUTADORA");
        $this->crearAsig(13, "ESTRUCTURA DE DATOS Y ALGORITMOS II");
        $this->crearAsig(13, "DISPOSITIVOS DE ALMACENAMIENTO Y ENTRADA-SALIDA");
        $this->crearAsig(13, "ADMINISTRACION DE PROYECTOS TIC");
        $this->crearAsig(13, "NEGOCIOS ELECTRONICOS Y DESARROLLO WEB");
        $this->crearAsig(13, "ADMINISTRACION DE SERVICIOS DE INTERNET");
        $this->crearAsig(13, "ARQUITECTURA CLIENTE SERVIDOR");
        $this->crearAsig(14, "INSTALACIONES ELECTRICAS");
        $this->crearAsig(14, "LAB. MAQUINAS ELECTRICAS I");
        $this->crearAsig(14, "LAB. MAQUINAS ELECTRICAS II");
        $this->crearAsig(14, "LAB. PROTECCION DE SISTEMAS ELECTRICOS");
        $this->crearAsig(14, "LAB. SISTEMAS ELECTRICOS DE POTENCIA I");
        $this->crearAsig(14, "LAB. SISTEMAS ELECTRICOS DE POTENCIA II");
        $this->crearAsig(14, "MAQUINAS ELECTRICAS I");
        $this->crearAsig(14, "MAQUINAS ELECTRICAS II");
        $this->crearAsig(14, "MAQUINAS ELECTRICAS III L");
        $this->crearAsig(14, "PLANTAS GENERADORAS");
        $this->crearAsig(14, "SISTEMAS ELECTRICOS DE POTENCIA II");
        $this->crearAsig(14, "SUBESTACIONES ELECTRICAS");
        $this->crearAsig(15, "PROCESAMIENTO DIGITAL DE SEÑALES");
        $this->crearAsig(15, "PROCESAMIENTO DIGITAL DE VOZ");
        $this->crearAsig(16, "ENERGIAS RENOVABLES");
        $this->crearAsig(16, "INTRODUCCION A LA CONVERSION DE ENERGIA");
        $this->crearAsig(16, "USO EFICIENTE EN EQUIPOS DE SERVICIO");
        $this->crearAsig(16, "PLANEACION E INSTALACION DE SISTEMAS BIOENERGETICOS");
        $this->crearAsig(17, "ADMINISTRACION Y REGULACION DE LAS TELECOMUNICACIONES");
        $this->crearAsig(17, "CAMPOS Y ONDAS");
        $this->crearAsig(17, "COMUNICACIONES DIGITALES");
        $this->crearAsig(17, "DISPOSITIVOS OPTICOS");
        $this->crearAsig(17, "FUNDAMENTOS DE SISTEMAS DE COMANDO Y MANEJO DE INFORMACION");
        $this->crearAsig(17, "LAB. ANTENAS");
        $this->crearAsig(17, "LAB. CIRCUITOS DE RADIOFRECUENCIA");
        $this->crearAsig(17, "LAB. DISPOSITIVOS DE MICROONDAS I");
        $this->crearAsig(17, "LAB. DISPOSITIVOS DE MICROONDAS II");
        $this->crearAsig(17, "LAB. FUNDAMENTOS DE SISTEMAS DE COMUNICACIONES");
        $this->crearAsig(17, "LAB. MEDIOS DE TRANSMISION");
        $this->crearAsig(17, "LAB. SISTEMAS DE COMUNICACIONES");
        $this->crearAsig(17, "LAB. SISTEMAS DE COMUNICACIONES ELECTRONICAS");
        $this->crearAsig(17, "LAB. SISTEMAS DE COMUNICACIONES OPTICAS");
        $this->crearAsig(17, "LAB. TEORIA ELECTROMAGNETICA");
        $this->crearAsig(17, "LAB. TRANSMISORES Y RECEPTORES");
        $this->crearAsig(17, "PRINCIPIOS PRACTICOS DE ELECTRONICA");
        $this->crearAsig(17, "REDES OPTICAS Y DE ACCESO");
        $this->crearAsig(17, "REGULACION DE LAS TELECOMUNICACIONES");
        $this->crearAsig(17, "SISTEMAS DE COMUNICACIONES");
        $this->crearAsig(17, "SISTEMAS DE COMUNICACIONES ELECTRONICAS");
        $this->crearAsig(17, "SISTEMAS DE RADIOCOMUNICACIONES II");
        $this->crearAsig(17, "TEMAS SELECTOS DE TELECOMUNICACIONES");
        $this->crearAsig(17, "TEORIA ELECTROMAGNETICA");
        $this->crearAsig(17, "DISPOSITIVOS DE RADIOFRECUENCIA");
        $this->crearAsig(17, "CIRCUITOS DE RADIOFRECUENCIA");
        $this->crearAsig(17, "CIRCUITOS DE RF");
        $this->crearAsig(17, "INTRODUCCION AL ANALISIS DE COMPATIBILIDAD ELECTROMAGNETICA");
        $this->crearAsig(17, "PROCESAMIENTO DE SEÑALES DIGITALES EN  TIEMPO REAL");
        $this->crearAsig(17, "TRANSMISORES Y RECEPTORES");
        $this->crearAsig(18, "ADMINISTRACION DE LA SEGURIDAD INDUSTRIAL  Y PROTECION AMBIENTAL");
        $this->crearAsig(18, "BOMBEO Y COMPRESION DE HIDROCARBUROS");
        $this->crearAsig(18, "COMERCIALIZACION DE CRUDO Y GAS NATURAL");
        $this->crearAsig(18, "COMPORTAMIENTO DE YACIMIENTOS");
        $this->crearAsig(18, "EQUIPO Y HERRAMIENTAS DE PERFORACION DE POZOS");
        $this->crearAsig(18, "EVALUACION DE PROYECTOS DE CIENCIAS DE LA TIERRA");
        $this->crearAsig(18, "FLUJO MULTIFASICO EN TUBERIA");
        $this->crearAsig(18, "FLUJO MULTIFASICO EN TUBERIAS");
        $this->crearAsig(18, "INGENIERIA DE PERFORACION DE POZOS");
        $this->crearAsig(18, "INTRODUCCION A LA INGENIERIA PETROLERA (2016)");
        $this->crearAsig(18, "LEGISLACION DE LA INDUSTRIA PETROLERA");
        $this->crearAsig(18, "MECANICA DE FLUIDOS");
        $this->crearAsig(18, "PERFORACION NO CONVENCIONAL");
        $this->crearAsig(18, "PLANEACION ADMINISTRACION DE PROYECTOS DE CIENCIAS DE LA TIERRA");
        $this->crearAsig(18, "PLANEACION Y EVALUACION DE PROYECTOS PETROLEROS");
        $this->crearAsig(18, "PRINCIPIOS DE MECANICA DE YACIMIENTOS");
        $this->crearAsig(18, "PROCESOS DE BOMBEO Y COMPRESION DE HIDROCARBUROS");
        $this->crearAsig(18, "PRODUCTIVIDAD DE POZOS");
        $this->crearAsig(18, "PROGRAMACION AVANZADA");
        $this->crearAsig(18, "PROPIEDADES DE LOS FUIDOS PETROLEROS");
        $this->crearAsig(18, "RECUPERACION SECUNDARIA Y MEJORADA");
        $this->crearAsig(18, "SIMULACION MATEMATICA DE YACIMIENTOS");
        $this->crearAsig(18, "SISTEMAS ARTIFICIALES DE PRODUCCION");
        $this->crearAsig(18, "TERMINACION Y MANTENIMIENTO DE POZOS");
        $this->crearAsig(18, "CARACTERIZACION ESTATICA Y DINAMICA DE YACIMIENTOS NATURALMENTE FRACTU");
        $this->crearAsig(19, "ABASTECIMIENTO  DE AGUA POTABLE");
        $this->crearAsig(19, "ALCANTARILLADO SANITARIO Y PLUVIAL");
        $this->crearAsig(19, "ENERGIA RENOVABLE EN EDIFICIOS");
        $this->crearAsig(19, "INGENIERIA AMBIENTAL I");
        $this->crearAsig(19, "INGENIERIA AMBIENTAL II");
        $this->crearAsig(19, "TRATAMIENTO DE AGUAS RESIDUALES");
        $this->crearAsig(19, "PROYECTOS SUSTENABLES DE INGENIERIA");
        $this->crearAsig(19, "LAB. ABASTECIMIENTO DE AGUA POTABLE");
        $this->crearAsig(19, "LAB. INGENIERIA AMBIENTAL I");
        $this->crearAsig(19, "LAB. TRATAMIENTO DE AGUAS RESIDUALES");
        $this->crearAsig(19, "LAB. ING AMBIENTAL II");
        $this->crearAsig(20, "AMPLIFICACION Y FILTRADO DE SEÑALES MEDICAS");
        $this->crearAsig(20, "ANALISIS DE BIOSEÑALES");
        $this->crearAsig(20, "BIOQUIMICA (2016)");
        $this->crearAsig(20, "ERGONOMIA");
        $this->crearAsig(20, "ESTANCIA");
        $this->crearAsig(20, "INSTALACIONES HOSPITALARIAS");
        $this->crearAsig(20, "MECANICA DEL CUERPO HUMANO");
        $this->crearAsig(20, "PLANEACION Y CONTROL DE RECURSOS HOSPITALARIOS");
        $this->crearAsig(20, "TEM SELEC ING SIST BIOMEDICOS I");
        $this->crearAsig(20, "TEM SELEC ING SIST BIOMEDICOS II");
        $this->crearAsig(20, "TEM SELEC ING SIST BIOMEDICOS IV");
        $this->crearAsig(20, "TEM SELEC ING SIST BIOMEDICOS VI");
        $this->crearAsig(20, "TEM SELEC ING SISTBIOMEDICOS III");
        $this->crearAsig(20, "INTRODUCCION A LA  ANATOMIA Y FISIOLOGIA I");
        $this->crearAsig(20, "INTRODUCCION A LA ANATOMIA Y FISIOLOGIA II");
        $this->crearAsig(20, "PSICOLOGIA MEDICA");
        $this->crearAsig(20, "BIOTERMOFLUIDOS I");
        $this->crearAsig(20, "ASPECTOS LEGALES Y ORGANZACIONALES ATENCION MEDICA");
        $this->crearAsig(20, "TEM SELEC ING SISTBIOMEDICOS VII");
        $this->crearAsig(20, "TEM SELEC AREA MEDICO BIOLOGICAS");
        $this->crearAsig(20, "BIOMATERIALES");
        $this->crearAsig(21, "AHORRO DE ENERGIA");
        $this->crearAsig(21, "DISEÑO DE SISTEMAS TERMICOS");
        $this->crearAsig(21, "ELEMENTOS DE MECANICA DEL MEDIO CONTINUO");
        $this->crearAsig(21, "LAB. MECANICA DE FLUIDOS I");
        $this->crearAsig(21, "LAB. MECANICA DE FLUIDOS II");
        $this->crearAsig(21, "LAB. TRANSFERENCA DE CALOR");
        $this->crearAsig(21, "LABORATORIO DE  AIRE ACONDICONADO Y REFRIGERACION");
        $this->crearAsig(21, "LABORATORIO DE MAQUINAS TERMICAS");
        $this->crearAsig(21, "LABORATORIO DE TERMOFLUIDOS");
        $this->crearAsig(21, "MECANICA DE FLUIDOS I");
        $this->crearAsig(21, "MECANICA DE FLUIDOS II");
        $this->crearAsig(21, "SISTEMAS DE CONVERSION DE ENERGIA TERMICA");
        $this->crearAsig(21, "SISTEMAS DE MEJORAMIENTO AMBIENTAL");
        $this->crearAsig(21, "SISTEMAS TERMOENERGETICOS");
        $this->crearAsig(21, "TEMAS SELECTOS DE TERMOFLUIDOS I");
        $this->crearAsig(21, "TERMODINAMICA APLICADA");
        $this->crearAsig(21, "TERMOFLUIDOS");
        $this->crearAsig(21, "TRANSFERENCIA DE CALOR");
        $this->crearAsig(21, "TURBOMAQUINARIA");
        $this->crearAsig(22, "ADMINISTRACION DE PROYECTOS");
        $this->crearAsig(22, "GEOMATICA BASICA");
        $this->crearAsig(22, "HIDROGRAFIA");
        $this->crearAsig(22, "LEGISLACION APLIC ING GEOMAT");
        $this->crearAsig(22, "PRACTICAS DE TOPOGRAFIA  (2016)");
        $this->crearAsig(22, "PRACTICAS DE TOPOGRAFIA II");
        $this->crearAsig(22, "PROYECTO GEOMETRICO DE OBRAS INFRAESTRUCTURA");
        $this->crearAsig(22, "TOPOGRAFIA APLICADA A LA CONSTRUCCION DE EDIFICIOS");
        $this->crearAsig(22, "TOPOGRAFIA DE YACIMIENTOS MINERALES");
        $this->crearAsig(22, "TOPOGRAFIA I  (2016)");
        $this->crearAsig(22, "TOPOGRAFIA III");
        $this->crearAsig(22, "TOPOGRAFIA II");
        $this->crearAsig(23, "ESTADISTICA APLICADA A INGENIERIA CIVIL");
        $this->crearAsig(23, "HIDRAULICA BASICA");
        $this->crearAsig(23, "HIDRAULICA DE CANALES");
        $this->crearAsig(23, "HIDRAULICA DE MAQUINAS Y TRANSITORIOS");
        $this->crearAsig(23, "HIDRAULICA URBANA");
        $this->crearAsig(23, "HIDROLOGIA");
        $this->crearAsig(23, "INGENIERIA DE COSTAS");
        $this->crearAsig(23, "MODELACIÓN COMPUTACIONAL EN HIDRÁULICA");
        $this->crearAsig(23, "OBRAS HIDRAULICAS");
        $this->crearAsig(23, "LAB. HIDROLOGIA");
        $this->crearAsig(23, "LAB. OBRAS HIDRAULICAS");
        $this->crearAsig(23, "LAB. HIDRAULICA BASICA");
        $this->crearAsig(23, "LAB. HIDRAULICA DE CANALES");
        $this->crearAsig(23, "LAB. HIDRAULICA DE MAQUINAS Y TRANSITORIOS");
        $this->crearAsig(23, "LAB. HIDRAULICA URBANA");
        $this->crearAsig(24, "AEROPUERTOS");
        $this->crearAsig(24, "CARRETERAS");
        $this->crearAsig(24, "EVALUACION DE PROYECTOS");
        $this->crearAsig(24, "INGENIERIA DE SISTEMAS I");
        $this->crearAsig(24, "INGENIERIA DE SISTEMAS II");
        $this->crearAsig(24, "INGENIERIA DE TRANSITO");
        $this->crearAsig(24, "INGENIERIA DEL TRANSPORTE I");
        $this->crearAsig(24, "INTEGRACION DE PROYECTOS");
        $this->crearAsig(24, "PLANEACION");
        $this->crearAsig(25, "ANALISIS ESPECTRAL DE SEÑALES");
        $this->crearAsig(25, "FISICA DE LAS ONDAS");
        $this->crearAsig(25, "FUNDAMENTOS DE TEORIA ELECTROMAGNETICA");
        $this->crearAsig(25, "INTRODUCCION A LA GEOFISICA");
        $this->crearAsig(25, "INTRODUCCION AL TRATAMIENTO DE SEÑALES");
        $this->crearAsig(25, "INTRODUCCION AL TRATAMIENTO SEÑALES");
        $this->crearAsig(25, "INVERSION DE DATOS GEOFISICOS");
        $this->crearAsig(25, "MECANICA DEL MEDIO CONTINUO");
        $this->crearAsig(25, "PROCESAMIENTO DE DATOS SISMICOS PETROLEROS");
        $this->crearAsig(25, "PROSPECCION ELECTRICA");
        $this->crearAsig(25, "PROSPECCION GRAVIMETRICA Y MAGNETOMETRICA");
        $this->crearAsig(25, "PROSPECCION SISMICA");
        $this->crearAsig(25, "PROSPECCION SISMICA I");
        $this->crearAsig(25, "PROSPECCION SISMICA II");
        $this->crearAsig(25, "SISMOLOGIA APLICADA A LA EXPLOTACION PETROLERA");
        $this->crearAsig(25, "SISMOLOGIA APLlCADA A LA EXPLORACION PETROLERA");
        $this->crearAsig(25, "TEMAS SEL. DE ING GEOFISICA I");
        $this->crearAsig(25, "TEMAS SEL. DE ING GEOFISICA II");
        $this->crearAsig(25, "TEMAS SELECTOS DE EXPLORACION MINERA");
        $this->crearAsig(25, "TEMAS SELECTOS DE EXPLORACION PETROLERA");
        $this->crearAsig(25, "TEMAS SELECTOS DE GEOTECNIA");
        $this->crearAsig(25, "PROYECTO TERMINAL");
        $this->crearAsig(26, "GEOLOGIA APLICADA A LA INGENIERIA CIVIL");
        $this->crearAsig(26, "GEOLOGIA DE MEXICO");
        $this->crearAsig(26, "GEOLOGIA ESTRUCTURAL");
        $this->crearAsig(26, "GEOLOGIA FISICA");
        $this->crearAsig(26, "GEOLOGIA GENERAL  (2016)");
        $this->crearAsig(26, "GEOMETRIA DESCRIPTIVA APLICADA");
        $this->crearAsig(26, "GEOTECNIA DE EXCAVACION");
        $this->crearAsig(26, "MECANICA DE ROCAS");
        $this->crearAsig(26, "MECANICA DE SUELOS");
        $this->crearAsig(26, "MECANICA DE SUELOS PARA CIENCIAS DE LA TIERRA");
        $this->crearAsig(26, "SISTEMAS DE INFORMACION GEOGRAFICA");
        $this->crearAsig(26, "SISTEMAS DE INFORMACION GEOGRAFICA I");
        $this->crearAsig(26, "TECNICAS GEOLOGICAS DE CAMPO");
        $this->crearAsig(26, "TEMAS SELECTOS DE INGENIERIA GEOLOGICA II");
        $this->crearAsig(27, "GEOESTADISTICA");
        $this->crearAsig(27, "GEOLOGIA APLICADA A LA MINERIA");
        $this->crearAsig(27, "GEOQUIMICA");
        $this->crearAsig(27, "GEOTECNIA DE EXCAVACION");
        $this->crearAsig(27, "MINERALOGIA");
        $this->crearAsig(27, "MINERALOGIA OPTICA");
        $this->crearAsig(27, "PETROLOGIA");
        $this->crearAsig(27, "PETROLOGIA IGNEA");
        $this->crearAsig(27, "PETROLOGIA METAMORFICA");
        $this->crearAsig(27, "PETROLOGIA SEDIMENTARIA");
        $this->crearAsig(27, "PROSPECCION Y EXPLORACION MINERA");
        $this->crearAsig(27, "EXPLORACION GEOQUIMICA MINERA");
        $this->crearAsig(27, "PROSPECCION MINERA");
        $this->crearAsig(27, "MINERALOGIA OPTICA Y TECNICA");
        $this->crearAsig(27, "YACIMIENTOS MINERALES");
        $this->crearAsig(27, "GEOQUIMICA APLlCADA");
        $this->crearAsig(28, "ESTRATIGRAFIA");
        $this->crearAsig(28, "GEOLOGIA DE PETROLEO");
        $this->crearAsig(28, "GEOLOGIA DE YACIMIENTOS DE FLUIDOS");
        $this->crearAsig(28, "GEOLOGIA DEL PETROLEO");
        $this->crearAsig(28, "GEOLOGIA Y GEOQUIMICA DEL PETROLEO");
        $this->crearAsig(28, "PALEONTOLOGIA GENERAL");
        $this->crearAsig(28, "SEDIMENTOLOGIA");
        $this->crearAsig(28, "TECTONICA");
        $this->crearAsig(28, "GEOLOGIA EXPLOTACION  DE PETROLEO,  AGUA Y  VAPOR");
        $this->crearAsig(29, "CIENCIA TECNOLOGIA Y SOCIEDAD");
        $this->crearAsig(29, "CULTURA Y COMUNICACION (2016)");
        $this->crearAsig(29, "ETICA PROFESIONAL");
        $this->crearAsig(29, "INTRODUCCION A LA ECONOMIA");
        $this->crearAsig(29, "INTRODUCCION AL ANALISIS ECONOMICO EMPRESARIAL");
        $this->crearAsig(29, "LITERATURA HISPANOAMERICANA CONTEMPORANEA");
        $this->crearAsig(29, "RECURSOS Y NECESIDADES DE MEXICO");
        $this->crearAsig(29, "REDACCION Y EXPOSICION DE TEMAS DE ING.(2016)");
        $this->crearAsig(29, "TALLER SOCIHUMANISTICO: LIDERAZGO");
        $this->crearAsig(29, "TALLER SOCIOHUMANISTICO:CREATIVIDAD");
        $this->crearAsig(30, "ANALlSIS FINANCIERO");
        $this->crearAsig(30, "CALIDAD");
        $this->crearAsig(30, "CONTABILIDAD FINANCIERA Y DE COSTOS");
        $this->crearAsig(30, "COSTOS Y EVALUACION DE PROYECTOS");
        $this->crearAsig(30, "CREATIVIDAD");
        $this->crearAsig(30, "CREATIVIDAD E INOVACION");
        $this->crearAsig(30, "DESARROLLO DE HABILIDADES DIRECTIVAS");
        $this->crearAsig(30, "DESARROLLO EMPRESARIAL");
        $this->crearAsig(30, "DIRECCION DE PROYECTOS");
        $this->crearAsig(30, "DISEÑO DE LA CADENA DE SUMINISTROS");
        $this->crearAsig(30, "DISEÑO DE SISTEMAS PRODUCTIVOS");
        $this->crearAsig(30, "ENVASE Y EMBALAJE");
        $this->crearAsig(30, "ERGONOMIA EN EL TRABAJO");
        $this->crearAsig(30, "ESTADISTICA APLICADA");
        $this->crearAsig(30, "ESTUDIO DEL TRABAJO");
        $this->crearAsig(30, "EVALUACION DE PROYECTOS DE INVERSION");
        $this->crearAsig(30, "FINANZAS COORPORATIVAS");
        $this->crearAsig(30, "INGENIERIA ECONOMICA");
        $this->crearAsig(30, "INGENIERIA INDUSTRIAL Y PRODUCTIVIDAD");
        $this->crearAsig(30, "INTELIGENCIA DE NEGOCIOS");
        $this->crearAsig(30, "INVESTIGACION DE OPERACIONES I");
        $this->crearAsig(30, "INVESTIGACION DE OPERACIONES II");
        $this->crearAsig(30, "LOGISTICA INVERSA");
        $this->crearAsig(30, "METODOLOGIA PARA LA PLANEACION");
        $this->crearAsig(30, "OPTIMIZACION DE OPERACIONES");
        $this->crearAsig(30, "PLANEACION Y CONTROL DE LA PRODUCCION");
        $this->crearAsig(30, "PRACTICAS PROFESIONALES PARA INGENIERIA INDUSTRIAL");
        $this->crearAsig(30, "PROCESOS INDUSTRIALES");
        $this->crearAsig(30, "RELACION LABORAL Y ORGANIZA");
        $this->crearAsig(30, "RELACIONES LABORALES Y ORGANIZACIONALES");
        $this->crearAsig(30, "SEGURIDAD INDUSTRIAL");
        $this->crearAsig(30, "SIMULACION");
        $this->crearAsig(30, "SISTEMAS DE CALIDAD");
        $this->crearAsig(30, "TEMAS SELECTOS DE LOGISTICA Y SISTEMAS");
        $this->crearAsig(30, "ADMINISTRACION");
        $this->crearAsig(30, "DESARROLLO DE HABILlDADES DIRECTIVAS");
        $this->crearAsig(30, "LEGISLACION INDUSTRIAL");
        $this->crearAsig(30, "SISTEMAS DE PLANEACION");
        $this->crearAsig(30, "ANALISIS Y MEJORA DE PROCESOS");
        $this->crearAsig(30, "COSTOS Y LOGISTICA DE SISTEMAS DE TRANSPORTE");
        $this->crearAsig(30, "TEMAS SELECTOS DE DIRECCION Y CREACION DE EMPRESAS");
        $this->crearAsig(31, "ANALISIS DE CIRCUITOS");
        $this->crearAsig(31, "AUTOMATIZACION INDUSTRIAL");
        $this->crearAsig(31, "CIRCUITOS DIGITALES");
        $this->crearAsig(31, "CONTROL AUTOMATICO");
        $this->crearAsig(31, "DISEÑO MECATRONICO");
        $this->crearAsig(31, "ELECTRONICA BASICA");
        $this->crearAsig(31, "INSTRUMENTACION");
        $this->crearAsig(31, "INSTRUMENTACION Y CONTROL");
        $this->crearAsig(31, "INTRODUCCION A SISTEMAS NO LINEALES");
        $this->crearAsig(31, "MAQUINAS ELECTRICAS");
        $this->crearAsig(31, "MODELADO DE SISTEMAS FISICOS");
        $this->crearAsig(31, "ROBOTICA");
        $this->crearAsig(31, "SISTEMAS ELECTRONICOS LINEALES");
        $this->crearAsig(31, "TECNICAS DE PROGRAMACION");
        $this->crearAsig(31, "TEMAS SEL DE PROGRAMACION II");
        $this->crearAsig(31, "TEMAS SELECTOS DE MECATRONICA I");
        $this->crearAsig(31, "TEMAS SELECTOS DE MECATRONICA II");
        $this->crearAsig(31, "TEMAS SELECTOS DE PROGRAMACION I");
    }

    public function crearAsig($depto_id, $nombre) {
        $asig = new Asignatura;
        $asig->depto_id = $depto_id;
        $asig->nombre = $nombre;
        $asig->save();
    }
}
